### à utiliser avec l'environnement "FLAIR-INC_cuda"
### ici : C:/_GLOBAL/TRAVAIL/OCS/cosia/FLAIR-1-main/FLAIR-1-main
### commande : flair-detect --conf=configs/flair-1-config-detect.yaml

###### modèle utilisé pour détecter les parkings

output_path: /content/flair_fnau/output/image_detect/
output_name: test_cosia_fnau.tif
input_img_path: "/content/flair_fnau/data/parking/subset.tif"
channels: [1, 2, 3]

img_pixels_detection: 512
margin: 128
output_type: "argmax"
n_classes: 19

model_weights: "/content/flair_fnau/model/FLAIR-INC_rgb_15cl_resnet34-unet_weights.pth"
model_framework:
  model_provider: SegmentationModelsPytorch
  HuggingFace:
    org_model:
  SegmentationModelsPytorch:
    encoder_decoder: resnet34_unet

batch_size: 6
use_gpu: true
num_worker: 0

write_dataframe: False

norma_task:
  - norm_type: custom
    norm_means: [105.08, 110.87, 101.82]
    norm_stds: [52.17, 45.38, 44]
