## Il faudrait à l'avenir, sur une machine avec plus de mémoire graphique
## - augmenter le nombre batchs (augmente le nombre d'éléments utilisés pour chaque itération au sein d'une époque) -> améliore la généralisation
## - diminuer le learning rate (0.0001)
## - augmenter le nombre d'epochs à 80 (avec 50 epochs, la meilleure était 49 donc il y a encore une marge de progression avec un earlystop à 20)

#### DATA PATHS
paths:
  out_folder: /content/flair_fnau/model/
  out_model_name: parking_fnau

  ######## TRAIN NEEDED
  train_csv: "/content/flair_fnau/data/parking/dataset_fnau/train.csv"
  val_csv: "/content/flair_fnau/data/parking/dataset_fnau/val.csv"
  ######## PREDICT (PATCH) NEEDED
  test_csv: "/content/flair_fnau/data/parking/dataset_fnau/test.csv"
  ckpt_model_path: "/content/flair_fnau/model/FLAIR-INC_rgb_15cl_resnet34-unet_weights.pth"

#### USAGE
tasks:
  train: True
  train_tasks:
    init_weights_only_from_ckpt: True
    resume_training_from_ckpt: False

  predict: True

  metrics: True
  delete_preds: False

#### TRAINING CONF
model_framework:
  model_provider: SegmentationModelsPytorch # HuggingFace or SegmentationModelsPytorch

  HuggingFace:
    org_model:

  SegmentationModelsPytorch:
    encoder_decoder: resnet34_unet

use_augmentation: True
use_metadata: False # Can be True if FLAIR dataset and SegmentationModelsPytorch model_provider

channels: [1, 2, 3] # starts at 1
norm_type: custom # [scaling, custom, without], default: scaling to range [0,1], see github readme
norm_means: [105.08, 110.87, 101.82]
norm_stds: [52.17, 45.38, 44]

seed: 2022

#### HYPERPARAMETERS
batch_size: 5
learning_rate: 0.5
num_epochs: 1

#### DATA CONF
use_weights: True
classes: # k = value in MSK : v = [weight, name]
  1: [1, "parking"]
  2: [0.65, "other"]

#### PREDICT CONF
georeferencing_output: True

#### COMPUTATIONAL RESSOURCES
accelerator: gpu # or cpu
num_nodes: 1
gpus_per_node: 1
strategy: "auto" # null if only one GPU, else 'ddp'
num_workers: 8

#### CKPT OPTIONS
ckpt_save_also_last: True
ckpt_verbose: False
ckpt_weights_only: False
ckpt_monitor: val_loss
ckpt_monitor_mode: min
ckpt_earlystopping_patience: 10

#### PRINT PROGRESS
cp_csv_and_conf_to_output: True
enable_progress_bar: True
progress_rate: 10
